Implement basic rl agents
NiklasAndMaxRL/IRL_project pull request #2
Opened 2022-08-01 19:17 UTC by SuperKoopa2109

PR for fixing git history.

2022-08-10 10:28 UTC, SuperKoopa2109 commented on GridWorld_environments.py
>                   walls: List[Tuple[int]] = [],
This is a test comment @maxserra

2022-08-10 10:41 UTC, SuperKoopa2109 commented on GridWorld_environments.py
>          self.possible_actions = [(1, 0), (0, 1), (-1, 0), (0, -1)]  # South, East, North, West
A test review.

2022-08-10 10:42 UTC, maxserra requested changes

2022-08-10 10:42 UTC, maxserra commented on IRL_agents.py
> +
How is this function any different from the one above?

2022-08-10 10:42 UTC, maxserra commented on GridWorld_environments.py
> +            self.goals = goals
Maybe we pass the % of walls, traps, int_goals and goals as a list/dict? or with additional arguments? So we can be flexible?
Right now, if the size is 4x4, there would be no traps nor anything :/

2022-08-10 10:42 UTC, maxserra commented on RL_arena.py
> +    parser.add_argument("-plt", "--plots", required=False, default=False, action="store_true")
Is this argument used? I think it should be used, not removed :)

2022-08-13 20:10 UTC, maxserra commented on RL_arena.py
> +        reward_func_preds.append(np_normalize(abs(deepcopy(env.get_board()))))
@SuperKoopa2109 why the `abs()` function??

2022-08-16 17:25 UTC, maxserra approved these changes

2022-08-16 17:26 UTC, merged